import type { Metadata } from "next";

import { getCopy } from "@/lib/content";
import {
  absoluteUrl,
  changelogPath,
  homePath,
  langs,
  privacyPath,
  termsPath,
  type Lang,
} from "@/lib/i18n";
import { getLegalCopy, type LegalPageKind } from "@/lib/legal";
import { site } from "@/lib/site";

/**
 * Per-locale <head> metadata.
 *
 * The hreflang set is the part worth getting right: three pages carrying the
 * same offer in three languages look like duplicates to a crawler unless each
 * one names all three plus an x-default. Every locale emits the full map, which
 * is what the spec asks for — the annotations have to be reciprocal.
 */

const OG_LOCALES: Record<Lang, string> = {
  en: "en_US",
  sk: "sk_SK",
  de: "de_DE",
};

/** One static card per locale; generated by tools/generate-og-images.mjs. */
const OG_IMAGES: Record<Lang, string> = {
  en: "/opengraph-image.png",
  sk: "/opengraph-image-sk.png",
  de: "/opengraph-image-de.png",
};

function languageAlternates(pathFor: (lang: Lang) => string) {
  const languages: Record<string, string> = {};
  for (const lang of langs) {
    languages[lang] = absoluteUrl(site.url, pathFor(lang));
  }
  languages["x-default"] = absoluteUrl(site.url, pathFor("en"));
  return languages;
}

export function homeMetadata(lang: Lang): Metadata {
  const copy = getCopy(lang);
  const title = `${site.name} — ${copy.meta.tagline}`;
  const url = absoluteUrl(site.url, homePath(lang));
  const image = {
    url: OG_IMAGES[lang],
    width: 1200,
    height: 630,
    alt: title,
  };

  return {
    metadataBase: new URL(site.url),
    title: {
      default: title,
      template: `%s · ${site.name}`,
    },
    description: copy.meta.description,
    applicationName: site.name,
    alternates: {
      canonical: url,
      languages: languageAlternates(homePath),
    },
    openGraph: {
      type: "website",
      url,
      siteName: site.name,
      title,
      description: copy.meta.description,
      locale: OG_LOCALES[lang],
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: copy.meta.description,
      images: [image],
    },
    robots: { index: true, follow: true },
  };
}

export function changelogMetadata(lang: Lang): Metadata {
  const copy = getCopy(lang);
  const url = absoluteUrl(site.url, changelogPath(lang));

  return {
    metadataBase: new URL(site.url),
    title: copy.changelog.title,
    description: copy.changelog.description,
    alternates: {
      canonical: url,
      languages: languageAlternates(changelogPath),
    },
    openGraph: {
      type: "article",
      url,
      siteName: site.name,
      title: `${copy.changelog.title} · ${site.name}`,
      description: copy.changelog.description,
      locale: OG_LOCALES[lang],
      images: [{ url: OG_IMAGES[lang], width: 1200, height: 630 }],
    },
    twitter: {
      card: "summary_large_image",
      title: `${copy.changelog.title} · ${site.name}`,
      description: copy.changelog.description,
      images: [{ url: OG_IMAGES[lang], width: 1200, height: 630 }],
    },
    robots: { index: true, follow: true },
  };
}

export function legalMetadata(kind: LegalPageKind, lang: Lang): Metadata {
  const copy = getLegalCopy(kind, lang);
  const pathFor = kind === "privacy" ? privacyPath : termsPath;
  const url = absoluteUrl(site.url, pathFor(lang));
  const title = `${copy.title} · ${site.name}`;
  const image = { url: OG_IMAGES[lang], width: 1200, height: 630, alt: title };

  return {
    metadataBase: new URL(site.url),
    title: copy.title,
    description: copy.description,
    alternates: {
      canonical: url,
      languages: languageAlternates(pathFor),
    },
    openGraph: {
      type: "website",
      url,
      siteName: site.name,
      title,
      description: copy.description,
      locale: OG_LOCALES[lang],
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: copy.description,
      images: [image],
    },
    robots: { index: true, follow: true },
  };
}
